source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'typhoeus', '~> 0.6.9'
gem 'yajl-ruby', require: 'yajl'
gem 'rails_12factor', group: :production


